# experiment configuration, naming makes data analysis easier
name: 'Compute AUROC for CIFAR10 and CIFAR100 with noise outliers. Evaluation with MSP, EBO and ODIN'
short_name: 'cifar_exp_3_noise'


# ---- general configuration ----


# which model? We only use wrn -> [wrn]
model: wrn
# which dataset to use? -> [cifar10, cifar100, imagenet]
#dataset_in: [cifar10,cifar100]
# which dataset to use as outliers? In our paper we use GAN_IMG, but 300K is supported for  cifar10 and cifar100 -> [GAN_IMG, 300K]
dataset_out: GAN_IMG
# epochs to train for
epochs: 10
# learning rate to use
learning_rate: 0.0005
# batch size for training
batch_size: 128
# batch size for outlier data
oe_batch_size: 128
# batch size for testing
test_bs: 128
# momentum for optimizer
momentum: 0.9
# weight decay for optimizer
decay: 0.0005


# ---- adversarial attacks on outliers ----


# adversarial attacks on outliers
# we sweep over it, so it will be set by the sweeper below
# adv_oe: -> [FGSM,EBA,PGD,MIFGSM,None]
# FGSM: Fast Gradient Sign Method
# EBA: Energy Based Attacks (Ours)
# PGD: Projected Gradient Descent
# MIFGSM: Momentum Iterative Fast Gradient Sign Method
# None: No adversarial attack -> Default Outlier Exposure

#adv_oe: EBA
# epsilon for adversarial attacks
# eps_oe: 0.5
# alpha for iterative attacks
alpha_oe: 0.03
# steps for iterative attacks
steps_oe: 20

# Number of outlier images to use | specific to the 64 batch size, thus we need a multiple of 64
n_out_images: 9984
# sigma for GAN_IMG
gan_sigma: 2.0


# ---- AUROC configuration ----


# Which AUROCs to compute
# train_auroc: compute auroc for OOD data during training
train_auroc: False
# test_auroc: compute auroc for OOD data after training
test_auroc: True
# adversarial_test_auroc: compute auroc for adversarial OOD data after training
adversarial_test_auroc: True 


# ---- hydra configuration ----


# hydra configuration for the sweeper
# sweepable parameters are defined here

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +adv_oe: EPS_GAUSS
      +eps_oe: 0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0
      +dataset_in: cifar10, cifar100